-- 1.
SELECT C_CARGA_HORARIA 
FROM CURSO 
WHERE C_NOME = 'Curso Geral de Ciências Sociais e Humanas';

-- 2.
SELECT A_ID, A_Nome, A_NUM_BI 
FROM ALUNO 
WHERE A_ID >= 5;

-- 3.
SELECT A_ID, A_Nome, A_MORADA, A_DN 
FROM ALUNO 
WHERE A_ID = 13;

-- 4.
SELECT A_MORADA, A_NUM_BI, A_DN 
FROM ALUNO 
WHERE A_Nome = 'Ana Marques';

-- 5.
SELECT A_Nome 
FROM ALUNO 
WHERE A_Nome LIKE 'A%';

-- 6.
SELECT * 
FROM DISCIPLINA 
WHERE D_ID > 100 AND D_ID < 300;

-- 7.
SELECT * 
FROM DISCIPLINA 
WHERE D_NOME LIKE 'I%';

-- 8.
SELECT * 
FROM DISCIPLINA 
WHERE D_NOME >= 'P';

-- 9.
SELECT * 
FROM CURSO 
WHERE C_NOME LIKE 'Curso Tecnológico%';

-- 10.
SELECT * 
FROM ALUNO 
WHERE A_DN BETWEEN '1985-01-01' AND '1988-12-31';

-- 11.
SELECT * 
FROM ALUNO 
WHERE A_NUM_BI BETWEEN 13000000 AND 15000000;

-- 12.
SELECT * 
FROM DISCIPLINA 
WHERE D_NOME LIKE '%ra%';

-- 13.
SELECT C_ID 
FROM CURSO 
WHERE C_NOME = 'Curso Tecnológico de Informática';

-- 14.
SELECT * 
FROM DISCIPLINA;

-- 15.
SELECT * 
FROM ALUNO 
WHERE A_MORADA LIKE 'Rua da Alegria%';

-- 16.
SELECT A_Nome, A_NUM_BI 
FROM ALUNO 
WHERE A_NUM_BI BETWEEN 13000000 AND 200000000;

-- 17.
SELECT * 
FROM ALUNO 
WHERE A_Nome LIKE '%sa%';

-- 18.
SELECT A_ID, A_Nome, A_MORADA 
FROM ALUNO 
WHERE A_DN IS NULL;

-- 19. 
SELECT A_ID, A_Nome, A_MORADA, A_DN, A_NUM_BI 
FROM ALUNO 
WHERE A_Nome IN ('António Pereira', 'Jorge Almeida');